version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installating dependencies for produce lambda..."
      - pip install -r requirements-produce.txt -t lib/produce
      - echo "Installating dependencies for s3 lambda..."
      - pip install -r requirements-s3.txt -t lib/s3
  build:
    commands:
      - echo "Zipping deployment package for produce lambda..."
      - cd lib/produce
      - zip -r9 ../../deployment_package_produce.zip .
      - cd ..
      - cd ..
      - cd ProduceAirbnbBookingData
      - zip -g ../deployment_package_produce.zip lambda_function.py
      - cd ..
      - echo "Zipping deployment package for s3 lambda..."
      - cd lib/s3
      - zip -r9 ../../deployment_package_s3.zip .
      - cd ..
      - cd ..
      - cd Airbnb-lambda-to-s3
      - zip -g ../deployment_package_s3.zip lambda_function.py
      - cd ..
      - echo "Zipping deployment package for filter lambda..."
      - cd ProcessFilteredBookings
      - zip -r9 ../deployment_package_filter.zip .
      - cd ..
  post_build:
    commands:
      - echo "Uploading produce zip to S3..."
      - aws s3 cp deployment_package_produce.zip s3://lambda-builds-zip-01/
      - echo "Updating Lambda function via S3..."
      - aws lambda update-function-code --function-name ProduceAirbnbBookingData --s3-bucket lambda-builds-zip-01 --s3-key deployment_package_produce.zip
      - echo "Deployment completed for produce lambda !! "
      - echo "Uploading s3 zip to S3..."
      - aws s3 cp deployment_package_s3.zip s3://lambda-builds-zip-01/
      - echo "Updating Lambda function via S3..."
      - aws lambda update-function-code --function-name Airbnb-lambda-to-s3 --s3-bucket lambda-builds-zip-01 --s3-key deployment_package_s3.zip
      - echo "Deployment completed for s3 lambda !! "
      - echo "Uploading filter zip to S3..."
      - aws s3 cp deployment_package_filter.zip s3://lambda-builds-zip-01/
      - echo "Updating Lambda function via S3..."
      - aws lambda update-function-code --function-name ProcessFilteredBookings --s3-bucket lambda-builds-zip-01 --s3-key deployment_package_filter.zip
      - echo "Deployment completed for filter lambda !! "
